In [4]:
import autograd.numpy as np
import pandas as pd
% matplotlib inline

In [13]:
from autograd import grad
from bokeh.plotting import output_notebook, figure, show
output_notebook()

Loading BokehJS ...

In [14]:
train = pd.read_csv('Income2.csv')[:23]
test = pd.read_csv('Income2.csv')[23:]

test.head()

Unnamed: 0  Education   Seniority     Income
23          24  10.413793   32.413793  18.570665
24          25  21.586207   20.000000  78.805784
25          26  11.241379   44.827586  21.388561
26          27  19.931034  168.965517  90.814035
27          28  11.655172   57.241379  22.636163

In [15]:
x_train_seniority = train['Seniority']
y_train_income = train['Income']
x_test_seniority = test['Seniority']
y_test_income = test['Income']

train_seniority_np = np.array(x_train_seniority)
train_income_np = np.array(y_train_income)
test_seniority_np = np.array(x_test_seniority)
test_income_np = np.array(y_test_income)

In [16]:
plot = figure(plot_width=300, plot_height=300, x_axis_label='Seniority', y_axis_label='Income')
plot.scatter(x=x_train_seniority, y=y_train_income, size=5)
show(plot)

In [18]:
w = np.array([0., 0.])

def model(x, w):
    return (w[1] * x) + w[0]

def loss(w):
    return np.sum(np.sqrt((model(train_seniority_np, w) - train_income_np)**2))

model_grad = grad(loss)

In [19]:
model(train_seniority_np, w)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [20]:
loss(w)

1557.9022277024469

In [21]:
model_grad(w)

array([  -23.        , -2353.10344828])

In [25]:
plot = figure(plot_width=300, plot_height=300, x_axis_label='Seniority', y_axis_label='Income')
plot.scatter(x=x_train_seniority, y=y_train_income, size=5)
plot.line(x=np.linspace(0,200,100), y=model(np.linspace(0,25,100), w), line_width=4, color='red', alpha=0.5)
show(plot)

In [49]:
for i in range(20000):
    w = w - (0.001 * model_grad(w))

In [50]:
plot = figure(plot_width=300, plot_height=300, x_axis_label='Seniority', y_axis_label='Income')
plot.scatter(x=x_train_seniority, y=y_train_income, size=5)
plot.line(x=np.linspace(0,200,100), y=model(np.linspace(0,25,100), w), line_width=5, color='red', alpha=0.5)
show(plot)

In [51]:
w

array([ 18.494     ,   0.12275862])

In [52]:
loss(w)

843.67649405122745