In [17]:
import autograd.numpy as np
import pandas as pd
% matplotlib inline

In [28]:
from autograd import grad
from bokeh.plotting import output_notebook, figure, show
output_notebook()

Loading BokehJS ...

In [91]:
train = pd.read_csv('Income1.csv')[:23]
test = pd.read_csv('Income1.csv')[23:]

test.head()

Unnamed: 0  Education     Income
23          24  19.511706  71.867195
24          25  19.913043  76.098135
25          26  20.354515  75.775218
26          27  20.755853  72.486055
27          28  21.157191  77.355021

In [87]:
x_train_education = train['Education']
y_train_income = train['Income']
x_test_education = test['Education']
y_test_income = test['Income']

train_education_np = np.array(x_train_education)
train_income_np = np.array(y_train_income)
test_education_np = np.array(x_test_education)
test_income_np = np.array(y_test_income)

In [80]:
plot = figure(plot_width=300, plot_height=300, x_axis_label='Education', y_axis_label='Income')
plot.scatter(x=x_train_education, y=y_train_income, size=5)
show(plot)

In [81]:
w = np.array([0., 0.])

def model(x, w):
    return (w[1] * x) + w[0]

def loss(w):
    return np.sum(np.sqrt((model(train_education_np, w) - train_income_np)**2))

model_grad = grad(loss)

In [82]:
model(train_education_np, w)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [83]:
loss(w)

978.40309364809866

In [84]:
model_grad(w)

array([ -23.       , -334.7090301])

In [85]:
plot = figure(plot_width=300, plot_height=300, x_axis_label='Education', y_axis_label='Income')
plot.scatter(x=x_train_education, y=y_train_income, size=5)
plot.line(x=np.linspace(0,25,100), y=model(np.linspace(0,25,100), w), line_width=4, color='red', alpha=0.5)
show(plot)

In [92]:
for i in range(20000):
    w = w - (0.001 * model_grad(w))

In [96]:
plot = figure(plot_width=300, plot_height=300, x_axis_label='Education', y_axis_label='Income')
plot.scatter(x=x_train_education, y=y_train_income, size=5)
plot.line(x=np.linspace(0,25,100), y=model(np.linspace(0,25,100), w), line_width=5, color='red', alpha=0.5)
show(plot)

In [94]:
w

array([-39.224     ,   5.64042809])

In [95]:
loss(w)

98.604668145659545

In [57]:
plot = figure(plot_width=300, plot_height=300, x_axis_label='Education', y_axis_label='Income')
plot.scatter(x=x_test_education, y=y_test_income, size=5)
show(plot)